# Generated by Django 3.2.8 on 2021-10-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='improvedusermodel',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='improvedusermodel',
            name='requestToExpert',
            field=models.ManyToManyField(blank=True, null=True, to='help.RequestForHelp', verbose_name='Запросы'),
        ),
    ]
