# Generated by Django 3.2.8 on 2021-10-23 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleRequest', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема запроса')),
                ('textRequest', models.TextField(blank=True, null=True, verbose_name='Текст запроса')),
                ('requiredSkill', models.CharField(blank=True, max_length=100, null=True, verbose_name='Требуемый навык')),
                ('nameIntern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя стажера')),
            ],
            options={
                'verbose_name': 'Запрос на помощь',
                'verbose_name_plural': 'Запросы на помощь',
            },
        ),
    ]
