# Generated by Django 3.2.8 on 2021-10-23 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRole', models.CharField(max_length=20, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSkill', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('descriptionSkill', models.TextField(blank=True, null=True, verbose_name='Описание навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionPortfolio', models.TextField(verbose_name='Описание портфолио')),
                ('achievementsPortfolio', models.TextField(verbose_name='Достижение')),
                ('participationInProjectPortfolio', models.TextField(verbose_name='Участие в проектах')),
                ('internPortfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя стажера')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='improvedUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя стажера')),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customUser.portfolio', verbose_name='Портфолио стажера')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customUser.role', verbose_name='Роль')),
                ('skills', models.ManyToManyField(blank=True, null=True, to='customUser.Skill', verbose_name='Навыки стажера')),
            ],
            options={
                'verbose_name': 'Профиль стажера',
                'verbose_name_plural': 'Профили стажеров',
            },
        ),
    ]
